{{- if .Values.storage.storageClassName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart-name" . }}-pvc
spec:
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
{{- end }}
