apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amazon-watcher-backend.fullname" . }}-secret
  labels:
    {{- include "amazon-watcher-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret }}

