apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-name" . }}
  labels:
    app: {{ include "chart-name" . }}
spec:
  selector:
    app: {{ include "chart-name" . }}
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
