{{- if and .Values.backend.enabled .Values.global.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "amazon-watcher-stack.fullname" . }}-storage
  labels:
    {{- include "amazon-watcher-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- range .Values.global.storage.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.global.storage.storageClassName }}
  storageClassName: {{ .Values.global.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.global.storage.size | quote }}
{{- end }}
