{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amazon-watcher-stack.fullname" . }}-backend-secret
  labels:
    {{- include "amazon-watcher-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  jwt-secret: {{ (.Values.secrets.jwtSecret | default "") | b64enc | quote }}
{{- end }}
