{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amazon-watcher-stack.fullname" . }}-db-secret
  labels:
    {{- include "amazon-watcher-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-password: {{ (.Values.secrets.databasePassword | default .Values.database.postgres.password) | b64enc | quote }}
{{- end }}
