{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "amazon-watcher-stack.db.serviceName" . }}
  labels:
    {{- include "amazon-watcher-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "amazon-watcher-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
