{{- if and .Values.ui.enabled .Values.ui.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "amazon-watcher-stack.fullname" . }}-ui
  labels:
    {{- include "amazon-watcher-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- if .Values.argocd.annotations }}
  annotations:
    {{- include "amazon-watcher-stack.argocd.annotations" . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "amazon-watcher-stack.fullname" . }}-ui
  minReplicas: {{ .Values.ui.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ui.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.ui.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ui.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.ui.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ui.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.ui.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.ui.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
