{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "amazon-watcher-stack.ui.serviceName" . }}
  labels:
    {{- include "amazon-watcher-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.ui.service.type "NodePort") .Values.ui.service.nodePort }}
      nodePort: {{ .Values.ui.service.nodePort }}
      {{- end }}
  selector:
    {{- include "amazon-watcher-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}
